import Head from "next/head";

const Meta: React.FC<{ title: string }> = ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/shared/logo.svg" />
    </Head>
  );
};
export default Meta;
